### Post login
# @name login
POST http://127.0.0.1:3000/api/user/login
content-type: application/json

{
  "username": "utta",
  "password": "bob12345"
}

### post homma
POST http://127.0.0.1:3000/api/restaurant/review
Authorization: Bearer {{login.response.body.token}}
content-Type: application/json

{
  "user_id": "234",
  "review_content": "oli ihan hyvä ruoka kiitos palvelusta tai jottai"
}

###

GET http://127.0.0.1:3000/api/restaurant/order
Authorization: Bearer {{login.response.body.token}}